<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Seminar</name>
   <tag></tag>
   <elementGuidId>27eda430-3ffe-484f-8387-8d83d0a9c634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/following::p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.primary-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Seminar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>804bc38a-b900-418a-93fa-d842bf983994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-color</value>
      <webElementGuid>6341a8e7-1a2f-461b-ac38-2dc6e674cf64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seminar</value>
      <webElementGuid>48dc6e83-975f-45ec-8281-69de39daf6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-htmlimports&quot;]/body[1]/div[@class=&quot;section-block sec1&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-12&quot;]/div[@class=&quot;top-btns&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-5 col-5&quot;]/div[@class=&quot;box&quot;]/a[1]/p[@class=&quot;primary-color&quot;]</value>
      <webElementGuid>389c7ddd-6f19-4e8b-99fd-0162f15b2c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/following::p[1]</value>
      <webElementGuid>1272dded-a98c-4688-917f-d1191ec11d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News letter'])[1]/following::p[1]</value>
      <webElementGuid>f048b4cf-bb1b-449c-ae5c-bb2d947162f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Announcement'])[1]/preceding::p[5]</value>
      <webElementGuid>652877d2-e296-4a7a-9c54-346248c8f016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seminar']/parent::*</value>
      <webElementGuid>7a513b95-2e6c-477d-a238-5b35f56e1689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>9949cbbc-e096-453b-aba1-247741d5ec8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Seminar' or . = 'Seminar')]</value>
      <webElementGuid>8c3aa741-4d7e-4a3d-8605-e0b1fe3e02f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
